# Generated by Django 5.2 on 2025-04-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Аталышы')),
                ('category', models.CharField(max_length=100, verbose_name='Категориясы')),
                ('year', models.IntegerField(verbose_name='Жылы')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Сүрөт')),
            ],
        ),
    ]
