# Generated by Django 5.2 on 2025-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Аталышы')),
                ('document', models.FileField(upload_to='projects/', verbose_name='Документ (PDF)')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Кошулган датасы')),
            ],
        ),
    ]
