# Generated by Django 5.2 on 2025-04-26 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='project',
            name='document',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Кошулган датасы'),
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/', verbose_name='PDF файлы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Аталуусу'),
        ),
    ]
